spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/department_db
    username: root
    password: root


eureka:
  #  client:
  #    serviceUrl:
  #      defaultZone: http://localhost:8761/eureka/
  instance:
    #    preferIpAddress: true
    #    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    #    leaseRenewalIntervalInSeconds: 5
    #    leaseExpirationDurationInSeconds: 10
    #    metadataMap.instanceId: ${spring.application.instance_id:${random.value}}
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
message: Hello, Department Service, this is a test message for cloud bus demo
