spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/employee_db
    username: root
    password: root

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      department-service:
        name: department-service

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
message: Hello, Employee Service
